= ASPECT-RATIO-FILTER.LRPLUGIN

This is a simple Lightroom Plugin which enables Adobe Lightroom to filter based on the aspect ratio of the photos. Basically the plugin just adds a custom metadata field - which is searchable - to all images and sets the value to the already existing aspect ration read from the metadata of the photo. When doing this the numeric aspect ratio is translated into a textual aspect ratio (e.g. 2:3). Additionally there the following options available to to reset the aspect ratio custom metadata via library action (Library -> Plugin Extras -> Aspect Ratio Filter)

Aspect Ratio Filter (current photos):: Aspect Ratio will be reset on all photos in the film strip or the selected photos.

Aspect Ratio Filter (all photos):: Aspect Ratio will be reset on all photos in the catalog.

== Versioning

This plugin follows link:https://semver.org/[Semantic Versioning 2.0.0]!

== Usage

Just download a release bundle or clone this repository to a location of your choice and add it via File -> Plugin Manager to Adobe Lightroom. When you add the plugin the first time, it will automatically update all of your pictures in the catalog with the custom aspect ratio metadata.

== Logging and Debug Infomation

If you want to enable logging create a config.lua file in:
windows:: C:\Users\${USERNAME}\AppData\Roaming\Adobe\Lightroom
mac:: ${HOME}/Library/Application Support/Adobe/Lightroom/config.lua

This file must have the following contents:
[source,lua]
----
include::./config.lua[]
----

Logfiles are then placed in:
windows:: C:\Users\${USERNAME}\Documents\LrClassicLogs\AspectRatioFilter.log
mac:: ${HOME}/Documents/LrClassicLogs/AspectRatioFilter.log

IMPORTANT: You must restart Adobe Lightroom for initialisation and changes on that file.

== TODO

. Strange error when using LrProgressScope
. Maybe add the possibility to view the Metadata in a custom TagSet

== Useful links

. link:https://www.adobe.io/apis/creativecloud/lightroomclassic.html[Lightroom SDK (Documention, Tutorials, API Spec, Examples)]
. link:https://feedback.photoshop.com/topics/lightroom-classic/5f5f2093785c1f1e6cc40872[Lightroom classic forum]
. link:https://www.lua.org/manual/5.4/[Lua reference manual]
. link:http://lua-users.org/wiki/[Lua wiki with lots of samples]

n
